version: 2.0

jobs:
  build-typescript:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Run build
          command: |
            ls -al
            npm install
            npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - "./"
  test-typescript:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run test
          command: |
            ls -la
            npm run test
      - persist_to_workspace:
          root: ./
          paths:
            - "./"
  deploy-typescript:
    docker:
      -image: cimg/node:lts
    steps:
      - attach_workspace:
        at: ./
      - run:
          name: Run deploy
          command: |
            ls -la

workflows:
  version: 2
  build-test:
    jobs:
      - build-typescript
      - test-typescript:
          requires: 
            - build-typescript
  build-test-deploy:
    jobs:
      - build-typescript
      - test-typescript:
          requires: 
            - build-typescript
      - deploy-typescript:
          requires:
            - test-typescript
